[project]
name = "jetbra-tools"
dynamic = ["version"]
authors = [
    { name = "delph1s", email = "admin@delph1s.com" }
]
maintainers = []
description = "Related tools for jetbra based on enthusiastic Mr. Big"
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["jetbra", "tools"]
requires-python = ">=3.10"
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "click>=8.1.8",
    "crypto-plus>=1.0.6",
    "httpx>=0.28.1",
    "typing-extensions>=4.12.2",
]
#packages = [{ include = "jbt", from = "src" }]
#include = [{ path = "tests", format = "sdist" }]

[project.urls]
Homepage = "https://github.com/delph1s/jetbra-tools/tree/python"
Documentation = "https://github.com/delph1s/jetbra-tools/tree/python/README.md"
Repository = "https://github.com/delph1s/jetbra-tools/tree/python"
Issues = "https://github.com/delph1s/jetbra-tools/issues"
Changelog = "https://github.com/delph1s/jetbra-tools/tree/python/CHANGELOG.md"

[dependency-groups]
dev = [
    "pylint >=2.17.4",
    "isort >=5.12.0",
    "pytest >=7.3.1",
    "tox >=4.5.2",
    "mkdocs >=1.4.3",
    "mkdocs-material >=8.5.11",
    "pytest-pylint >=0.19.0",
    "pre-commit >=3.3.2",
    "pytest-mock >=3.10.0",
    "pytest-cov >=4.1.0",
]
lint = [
    "ruff"
]

[project.optional-dependencies]
server = [
    "fastapi[all]",
]

[project.scripts]
jbt = "jbt.cmdline:main"

#[build-system]
#requires = ["hatchling"]
#build-backend = "hatchling.build"

[tool.uv]
# 使用 uv 管理项目环境
managed = true
# 是否打包项目
package = false
# 默认安装
default-groups = []

#[[tool.uv.index]]
#name = "testpypi"
#url = "https://test.pypi.org/simple/"
#publish-url = "https://test.pypi.org/legacy/"

[tool.pylint.design]
max-line-length = 120

# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html
[tool.black]
line-length = 120
target-version = ["py310", "py311", "py312"]
skip-string-normalization = false
skip-magic-trailing-comma = false
include = ["tests", "src"]
#exclude = []
#extend-exclude = []
#force-exclude = []
workers = 20
quiet = false
verbose = false
